name: build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  full_ci:
    runs-on: ubuntu-18.04

    steps:
      - name : checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31

      - name: run tests
        run: go test -json ./... > test.json

      - name: annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.1
        with:
          test-results: test.json
